import Register from "@/components/auth/register";

export const metadata = {
  title: "Register Page",
  description: "Generated by Syed Shazeedul Islam",
};

export default function Page() {
  return (
    <Register />
  );
}
