import Login from "@/components/auth/login";

export const metadata = {
  title: "Login Page",
  description: "Generated by Syed Shazeedul Islam",
};

export default function Page() {
  return (
    <Login />
  );
}
