export const metadata = {
  title: "Dashboard Page",
  description: "Generated by Syed Shazeedul Islam",
};

export default function Page() {
  return <h1 className="text-black dark:text-white">Hello, Dashboard Page!</h1>;
}
