import Dashboard from "@/components/dashboard/dashboard.jsx";

export const metadata = {
  title: "Dashboard Page",
  description: "Generated by Syed Shazeedul Islam",
};

export default function Page() {
  return (
    <Dashboard />
  );
}
